# SPDX-License-Identifier: GPL-2.0
# Seekwave SWT6621S in-tree Makefile

obj-$(CONFIG_SEEKWAVE_BSP_DRIVERS) += seekwaveplatform_lite/
obj-$(CONFIG_WLAN_VENDOR_SWT6621S) += swt6621s_wifi/
obj-$(CONFIG_SKW_BT)               += swtbt4l/
