#
#SeekWave Platform Drivers Makefile
#
#
ifdef CONFIG_SEEKWAVE_BSP_DRIVERS
obj-$(CONFIG_SKW_USB)               += usb/
obj-$(CONFIG_SKW_SDIOHAL)           += sdio/
obj-$(CONFIG_SEEKWAVE_BSP_DRIVERS)  += skwutil/
endif
